### ISSUE TITLE
login error

### ISSUE THREAD

**Issue by ahoussam** [hgdiaz/aspnetcore.ldap#1]
Object reference not set to an instance of an object.

Excuse me
![error_ldapApp](https://user-images.githubusercontent.com/620739/174284564-5169161d-1578-4f89-ba19-de028f4d3bf4.PNG)

How do we solve this problem? What is the reason for its appearance? 
thank you

**Comment by hgdiaz** [comment]
Hello ahousam.

It's hard to detect the problem with this information, but I can suggest you to do this:
1) Check all the values under appsettings.json
2) Put a breakpoint in the Login method (HttpPost) under the AccountController
3) Also in the LdapAuthenticationService class, put a breakpoint at the Login method.
4) Run the program and try to login
Probably the _connection.Search is not returning any result because of a misconfiguration in the AD

Tell me if you can solve the problem.....

**Comment by ahoussam** [comment]
Thanks for help
I tried to do all the things they wrote in this note.. and I didn't succeed in identifying the error, here is a picture of it
! [error_ldap](https://user-images.githubusercontent.com/620739/176140333-3e05c550-d35b-4e84-8143-298d80cb0223.PNG)
at Debug

**Comment by hgdiaz** [comment]
You should put a breakpoint at the first line and go step by step, so you can detect which one is the null variable that you are trying to read. Maybe claimsIdentity or HttpContext
